version: "3"
networks:
  bittery-net:

services:

  btcpayserver:
    restart: unless-stopped
    image: btcpayserver/btcpayserver:1.0.6.0
    container_name: btcpayserver
    environment:
      BTCPAY_POSTGRES: User ID=${POSTGRES_USER};Host=postgres;Port=5432;Database=${POSTGRES_DB};Password=${POSTGRES_PASSWORD}
      BTCPAY_NETWORK: ${BITCOIN_NETWORK}
      BTCPAY_BIND: 0.0.0.0:49392
      BTCPAY_ROOTPATH: /
      BTCPAY_SSHCONNECTION: "root@host.docker.internal"
      BTCPAY_DEBUGLOG: btcpay.log
      BTCPAY_CHAINS: "btc"
      BTCPAY_BTCEXPLORERURL: http://nbxplorer:32838/
      BTCPAY_BTCLIGHTNING: "type=lnd-rest;server=http://localhost:8080/;macaroonfilepath=/etc/lnd_bitcoin/emergencja/bitcoin/datadir/admin.macaroon;allowinsecure=true"
    volumes:
    - ../volumes/btcpay/datadir:/datadir
    - ../volumes/nbxplorer/datadir:/root/.nbxplorer
    networks:
      - bittery-net
    expose:
      - 49392

  bitcoind:
    restart: unless-stopped
    container_name: bitcoind
    image: btcpayserver/bitcoin:0.20.1
    environment:
      BITCOIN_NETWORK: ${BITCOIN_NETWORK}
      BITCOIND_RPC_USER: ${BITCOIND_RPC_USER}
      BITCOIND_RPC_PASSWORD: ${BITCOIND_RPC_PASSWORD}
      BITCOIN_WALLETDIR: "/walletdata"
      BITCOIN_EXTRA_ARGS: |
        rpcssl=1
        rpcport=43783
        rpcbind=0.0.0.0:43783
        port=39388
        whitelist=0.0.0.0/0
        zmqpubrawblock=tcp://0.0.0.0:28334
        zmqpubrawtx=tcp://0.0.0.0:28335
        rpcuser=${BITCOIND_RPC_USER}
        rpcpassword=${BITCOIND_RPC_PASSWORD}
        prune=50000
        rpcthreads=300
    volumes:
    - ../volumes/bitcoind/datadir:/data
    - ../volumes/bitcoind/wallet_datadir:/walletdata
    networks:
      - bittery-net
    ports:
      # rpc
      - 43783:43783
      # zmqpubrawblock
      - 28334:28334
      # zmqpubrawtx
      - 28335:28335
      - 8333:8333

  nbxplorer:
    restart: unless-stopped
    container_name: nbxplorer
    image: nicolasdorier/nbxplorer:2.1.44
    environment:
      NBXPLORER_NETWORK: ${BITCOIN_NETWORK}
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_SIGNALFILESDIR: /datadir
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_BTCRPCURL: http://bitcoind:43782/
      NBXPLORER_BTCNODEENDPOINT: bitcoind:39388
      NBXPLORER_BTCRPCUSER: ${BITCOIND_RPC_USER}
      NBXPLORER_BTCRPCPASSWORD: ${BITCOIND_RPC_PASSWORD}
    volumes:
    - ../volumes/nbxplorer/datadir:/datadir
    - ../volumes/bitcoind/datadir:/root/.bitcoin
    networks:
      - bittery-net
    expose:
    - 32838

  postgres:
    restart: unless-stopped
    container_name: postgres
    image: postgres:13-alpine
    volumes:
      - ../volumes/postgres/datadir:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - bittery-net
    ports:
      - 5431:5432

  nginx:
    restart: unless-stopped
    image: nginx:1.19.4
    container_name: nginx
    volumes:
      - ../volumes/nginx/conf:/etc/nginx/conf.d:rw
      - ../volumes/nginx/vhost:/etc/nginx/vhost.d
      - ../volumes/nginx/html:/usr/share/nginx/html
      - ../volumes/nginx/certs:/etc/nginx/certs:ro
    networks:
      - bittery-net
    ports:
      - 80:80
      - 81:81
      - 443:443

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 9000:8080
#    networks:
#      - bittery-net

